export const GET_PRODUCTS_SUCCES = "GET_ALL_PRODUCTS_BEGIN";
export const GET_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_BEGIN";
export const GET_SINGLE_PRODUCT_SUCCES = "GET_SINGLE_PRODUCT_SUCCES";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
